name: GitHub Actions Demo
run-name: gendiff test workflow
on: [push]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: make install
      - run: make publish
      - run: make lint
      - run: make test
